site_name: RxFusion
pages:
  - Home: index.md
  - RxFusion Language: language.md
  - Platforms:
    - Arduino: arduino.md
    - UDOO Neo: udoo-neo.md
  - API Summary: api-reference.md
  - API Reference:
    - Methods: methods.md
    - Classes: classes.md
    - Operators: operators.md
repo_url: https://github.com/sathibault/RxFusion.git
theme: readthedocs
